_unauthorised:
    path: /unauthorised
    defaults: { _controller: DeesonWardenBundle:Dashboard:unauthorised }

_dashboard:
    path:  /
    defaults: { _controller: DeesonWardenBundle:Dashboard:index }

sites_list:
    path:    /sites
    defaults: { _controller: DeesonWardenBundle:Site:index }

sites_add:
    path:    /sites/add
    defaults: { _controller: DeesonWardenBundle:Site:add }

sites_show:
    path:    /sites/{id}
    defaults: { _controller: DeesonWardenBundle:Site:show }

sites_edit:
    path:    /sites/{id}/edit
    defaults: { _controller: DeesonWardenBundle:Site:edit }

sites_delete:
    path:    /sites/{id}/delete
    defaults: { _controller: DeesonWardenBundle:Site:delete }

sites_update_refresh:
    path:    /sites/{id}/refresh
    defaults: { _controller: DeesonWardenBundle:Site:refresh }

sites_logs:
    path:    /sites/{id}/logs
    defaults: { _controller: DeesonWardenBundle:Site:logs }

public_key:
    path:    /public-key
    defaults: { _controller: DeesonWardenBundle:Site:publickey }

sites_update:
    path:    /site-update
    defaults: { _controller: DeesonWardenBundle:Site:update }

admin_user_list:
    path:    /admin/user/list
    defaults: { _controller: DeesonWardenBundle:User:list }

admin_user_add:
    path:    /admin/user/new
    defaults: { _controller: DeesonWardenBundle:User:new }

admin_user_edit:
    path:    /admin/user/{id}/edit
    defaults: { _controller: DeesonWardenBundle:User:edit }

admin_user_delete:
    path:    /admin/user/{id}/delete
    defaults: { _controller: DeesonWardenBundle:User:delete }

admin_user_change_password:
    path:    /admin/user/{id}/change-password
    defaults: { _controller: DeesonWardenBundle:User:changepassword }

admin_user_group_list:
    path:    /admin/group/list
    defaults: { _controller: warden.group.controller:listAction }

admin_user_group_new:
    path:    /admin/group/new
    defaults: { _controller: warden.group.controller:newAction }

admin_user_group_edit:
    path:    /admin/group/{id}/edit
    defaults: { _controller: warden.group.controller:editAction }

admin_user_group_delete:
    path:    /admin/group/{id}/delete
    defaults: { _controller: warden.group.controller:deleteAction }
