services:
    kernel.listener.warden_exception_listener:
        class: Deeson\WardenBundle\Listener\ExceptionListener
        arguments: ['@templating', '@kernel']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    warden_setup:
        class: Deeson\WardenBundle\Services\WardenSetupService
        arguments: ['%kernel.root_dir%']

    assets.date_version_strategy:
        class: Deeson\WardenBundle\Asset\VersionStrategy\DateVersionStrategy
        public: false

    warden.user_provider:
        class: Deeson\WardenBundle\Security\WebserviceUserProvider
        arguments: ['%kernel.root_dir%']
        public: true

    warden.form_login_authenticator:
        class: Deeson\WardenBundle\Security\FormLoginAuthenticator
        arguments: ['@router', '@security.password_encoder']

    warden.http_client:
        class: Deeson\WardenBundle\Client\GuzzleHttpRequestHandler

    warden.mail_manager:
        class: Deeson\WardenBundle\Services\MailService
        arguments: ['@mailer', '@twig']

    warden.ssl_encryption:
        class: Deeson\WardenBundle\Services\SSLEncryptionService
        arguments: ['%public_key_file%', '%private_key_file%']
        public: true

    warden.form.profile:
        class: Deeson\WardenBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: warden_user_profile }

    warden.site_manager:
        class: Deeson\WardenBundle\Managers\SiteManager
        arguments: ['@doctrine_mongodb', '@monolog.logger']
        public: true

    warden.site_request_log_manager:
        class: Deeson\WardenBundle\Managers\SiteRequestLogManager
        arguments: ['@doctrine_mongodb', '@monolog.logger', '@arturdoruch_paginator']
        public: true

    warden.site_connection:
        class: Deeson\WardenBundle\Services\SiteConnectionService
        arguments: ['@warden.http_client', '@warden.ssl_encryption', '@monolog.logger', '@warden.site_request_log_manager', '%kernel.environment%']

    warden.dashboard_manager:
        class: Deeson\WardenBundle\Managers\DashboardManager
        arguments: ['@doctrine_mongodb', '@monolog.logger', '@warden.site_manager', '@warden.mail_manager', '@service_container']
        public: true
        tags:
            - { name: kernel.event_listener, event: warden.dashboard.update, method: onWardenDashboardUpdate }
            - { name: kernel.event_listener, event: warden.cron, method: onWardenCron, priority: -100 }
            - { name: kernel.event_listener, event: warden.site.refresh, method: onWardenSiteRefresh, priority: 100 }
