imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 3600
    fragments:       ~
    http_method_override: true
    assets:
        version_strategy: 'assets.date_version_strategy'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Mongodb Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%db_host%:%db_port%/%db_name%
            options:
                username: "%db_username%"
                password: "%db_password%"
    default_database:     "%db_name%"
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      '%mailer_port%'
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool: { type: memory }

artur_doruch_paginator:
    limit: 10
    prev_page_label: 'Previous'
    next_page_label: 'Next'
