security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        webservice:
            id: warden.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login$
            security: false
        add_site:
            pattern:  ^/sites/add
            security: false
        public_key:
            pattern:  ^/public-key
            security: false
        sites_update:
            pattern:  ^/site-update
            security: false
        secured_area:
            pattern: ^/
            guard:
                authenticators:
                    - warden.form_login_authenticator
            form_login:
                check_path: security_login_check
                login_path: login
            logout:
                path: /logout
                target: /
            logout_on_user_change: true

    access_denied_url: /unauthorised

    access_control:
        - { path: ^/, roles: ROLE_USER, requires_channel: "%protocol%" }
